services:
  postgres:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: restaurant-api
    ports:
      - '5432:5432'
    profiles:
      - db
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U user -d token-based-auth-v1' ]
      interval: 10s
      timeout: 5s
      retries: 5
  cache:
    image: redis:latest
    container_name: redist_container
    restart: always
    ports:
      - "6379:6379"
    command: >
      --requirepass Secret123
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "Secret", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis_data:/data
    profiles:
      - db
  redis_insight:
    image: redislabs/redisinsight:latest
    container_name: redis_insight
    ports:
      - "5540:5540"
    depends_on:
      cache:
        condition: service_healthy
    profiles:
      - db
  seq:
    image: datalust/seq:latest
    environment:
      ACCEPT_EULA: Y
      SEQ_FIRSTRUN_ADMINPASSWORD: Secret123
    ports:
      - "5341:80"
    volumes:
      - seq-data:/data
    profiles:
      - logging
  localstack:
    image: localstack/localstack:latest
    container_name: localstack-s3
    ports:
      - "4566:4566"
    environment:
      - DEBUG=1
      - SERVICES=s3
      - AWS_DEFAULT_REGION=eu-west-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/localstack/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh
      - localstack_data:/var/lib/localstack
    profiles:
      - localstack
    healthcheck:
      test: [ "CMD", "awslocal", "s3", "ls" ]
      interval: 5s
      timeout: 10s
      retries: 5
  

volumes:
  postgres_data:
  redis_data:
  seq-data:
  localstack_data: