services:
  postgres:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: restaurant-api
    ports:
      - '5432:5432'
    profiles:
      - db
      - dev
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U user -d token-based-auth-v1' ]
      interval: 10s
      timeout: 5s
      retries: 5
  cache:
    image: redis:latest
    container_name: redist_container
    restart: always
    ports:
      - "6379:6379"
    command: >
      --requirepass Secret123
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "Secret", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis_data:/data
    profiles:
      - db
      - dev
  redis_insight:
    image: redislabs/redisinsight:latest
    container_name: redis_insight
    ports:
      - "5540:5540"
    depends_on:
      cache:
        condition: service_healthy
    profiles:
      - db
      - dev
  seq:
    image: datalust/seq:latest
    environment:
      ACCEPT_EULA: Y
      SEQ_FIRSTRUN_ADMINPASSWORD: Secret123
    ports:
      - "5341:80"
    volumes:
      - seq-data:/data
    profiles:
      - logging
      - dev
  minio:
    image: minio/minio:latest
    container_name: minio-s3
    ports:
      - "9000:9000" 
      - "9001:9001" 
    environment:
      MINIO_ROOT_USER: test
      MINIO_ROOT_PASSWORD: testpassword
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    profiles:
      - localstack
      - dev
    healthcheck:
      test: [ "CMD", "mc", "ready", "local" ]
      interval: 5s
      timeout: 5s
      retries: 5
  createbuckets:
    image: minio/mc:latest
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 test testpassword;
      /usr/bin/mc mb myminio/images-bucket;
      /usr/bin/mc anonymous set download myminio/images-bucket;
      exit 0;
      "
    profiles:
      - localstack
      - dev

volumes:
  postgres_data:
  redis_data:
  seq-data:
  minio_data:
    driver: local