namespace RestaurantApi.Application.Common.Enums;

public enum Codes
{
    FETH_DATA_SUCCESS,
    CONTENT_CREATED_SUCCESS,
    VALIDATION_ERROR,
    UNAUTHORIZED,
    NOT_FOUND,
    CONFLICT,
    LOGIN_SUCCESS,
    MAIL_VERIFICATION_REQUIRED,
    FORBIDDEN,
    TWO_FACTOR_REQUIRED,
    MAIL_VERIFIED_SUCCESS,
    BAD_REQUEST
}